{% if grains['os'] == "Gentoo" %}
acpid: sys-power/acpid
apache: www-servers/apache
atop: sys-process/atop
cpufrequtils: sys-power/cpufrequtils
cron: sys-process/cronie
dhcpd: net-misc/dhcp
dovecot: net-mail/dovecot
exim: mail-mta/exim
fping: net-analyzer/fping
git: dev-vcs/git
htop: sys-process/htop
ifstat: net-analyzer/ifstat
imapproxy: net-mail/up-imapproxy
ipset: net-firewall/ipset
iptables: net-firewall/iptables
iptraf-ng: net-analyzer/iptraf-ng
irqbalance: sys-apps/irqbalance
keepalived: sys-cluster/keepalived
kerberos: app-crypt/mit-krb5
lsof: sys-process/lsof
lvm2: sys-fs/lvm2
mariadb: dev-db/mariadb
mcelog: app-admin/mcelog
memcached: net-misc/memcached
mlocate: sys-apps/mlocate
mongodb: dev-db/mongodb
mysql: dev-db/mysql
nagios: net-analyzer/nagios
named: net-dns/bind
nginx: www-servers/nginx
ntp: net-misc/ntp
openvpn: net-misc/openvpn
pdsh: app-shells/pdsh
php: dev-lang/php
postfix: mail-mta/postfix
redis: dev-db/redis
redmine: www-apps/redmine
rsync: net-misc/rsync
rsyslog: app-admin/rsyslog
salt: app-admin/salt
samba: net-fs/samba
saslauthd: dev-libs/cyrus-sasl
slapd: net-nds/openldap
snmpd: net-analyzer/net-snmp
spamd: mail-filter/spamassassin
spawn_fcgi: www-servers/spawn-fcgi
sshd: net-misc/openssh
strace: dev-util/strace
sudo: app-admin/sudo
svscan: sys-process/daemontools
tcpdump: net-analyzer/tcpdump
tftpd: net-ftp/tftp-hpa
tmux: app-misc/tmux
traceroute: net-analyzer/traceroute
uwsgi: www-servers/uwsgi
{% elif grains['os'] == "Ubuntu" %}
exim: exim4
named: bind9
redis: redis-server
sshd: openssh-server
svscan: daemontools-run
tftpd: tftpd-hpa
{% elif grains['os'] == "CentOS" %}
cron: cronie
named: bind
snmpd: net-snmp
sshd: openssh-server
svscan: daemontools
{% endif %}
