#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
import yaml
import traceback

from os import path as osp

conf_dir = osp.join(osp.realpath(__file__), "utils")
if conf_dir not in sys.path:
    sys.path.insert(0, conf_dir)

from utils import ldap_ops as ldap_ops

if __name__ == "__main__":
    try:
        slapd = ldap_ops.ldap_ops()
        if osp.exists("user.yaml"):
            for user in yaml.load_all(open("user.yaml", "r")):
                sn = user.get("sn")
                givenName = user.get("givenName")
                user['cn'] = " ".join((sn, givenName))
                user['gecos'] = user['cn']
                slapd.user_add(user)

        slapd.update_group_from_users()

    except ldap_ops.LDAPError as e:
        print("!! %s" % e)
